# ---------------------------------------------------------------------------
# Database credentials are generated by Terraform and stored in AWS Secrets
# Manager. They are never written to the repo or to user-data in plaintext;
# EC2 instances read them at boot using their IAM role.
# ---------------------------------------------------------------------------

resource "random_password" "db" {
  length  = 20
  special = false # alphanumeric keeps it safe in shell/env without escaping
}

resource "random_id" "secret_suffix" {
  byte_length = 4
}

resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}-db-credentials-${random_id.secret_suffix.hex}"
  description = "MySQL credentials for the student records app"

  # 0-day recovery window so teardown + re-deploy in a demo doesn't hit the
  # "secret scheduled for deletion" name conflict. Use a longer window in prod.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}
